export const UPDATEMENULIST ='UPDATEMENULIST';
export const UPDATECOLLAPSE ='UPDATECOLLAPSE';
export const SETCURRENTMENU ='SETCURRENTMENU';
export const DELETECURRENTMENU ='DELETECURRENTMENU';
export const TOOGLECURRENTMENU ='TOOGLECURRENTMENU';

